name: Acquire activation file
on:
  workflow_dispatch: {}
jobs:
  activation:
        runs-on: ubuntu-latest
        steps: 
            - name: Unity - Activate
              uses: game-ci/unity-activate@v1.3
